# Generated by Django 4.2.9 on 2024-02-25 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('domicilio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=400, null=True)),
                ('ficha_medica', models.BooleanField(default=False)),
                ('beca', models.BooleanField(default=False)),
                ('descuento', models.PositiveIntegerField(blank=True, null=True)),
                ('responsable1_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable1_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable1_vinculo', models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Tio', 'Tio')], max_length=20, null=True)),
                ('responsable1_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable1_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('responsable2_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable2_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable2_vinculo', models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Tio', 'Tio')], max_length=20, null=True)),
                ('responsable2_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable2_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('responsable3_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable3_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable3_vinculo', models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Tio', 'Tio')], max_length=20, null=True)),
                ('responsable3_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable3_email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('saldo', models.IntegerField(default=0)),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'), ('Gasto', 'Gasto'), ('Ajuste', 'Ajuste')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_semanales', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=20)),
                ('anio', models.PositiveIntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_clase', models.PositiveIntegerField()),
                ('precio_semana_1', models.PositiveIntegerField()),
                ('precio_semana_2', models.PositiveIntegerField()),
                ('precio_semana_3', models.PositiveIntegerField()),
                ('precio_libre', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='AppDanzaVida.alumno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='AppDanzaVida.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('libre', models.BooleanField(default=True)),
                ('cantidad_horas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='AppDanzaVida.sucursal')),
            ],
            options={
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario',
            field=models.ManyToManyField(blank=True, to='AppDanzaVida.horariodisciplina'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='AppDanzaVida.sucursal'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='AppDanzaVida.tipodisciplina'),
        ),
        migrations.CreateModel(
            name='DetallePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_nombre', models.CharField(max_length=20)),
                ('dia_numero', models.PositiveIntegerField()),
                ('asistencia_tomada', models.BooleanField(default=False)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppDanzaVida.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pagada', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDanzaVida.alumno')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppDanzaVida.cuota')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDanzaVida.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_caja', to='AppDanzaVida.caja')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_caja', to='AppDanzaVida.categoriacaja')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_asistencia', to='AppDanzaVida.alumno')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppDanzaVida.asistencia')),
                ('detalle_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_asistencia', to='AppDanzaVida.detalleperiodo')),
            ],
        ),
        migrations.AddField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='AppDanzaVida.periodo'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='AppDanzaVida.sucursal'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='AppDanzaVida.disciplina'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='AppDanzaVida.periodo'),
        ),
    ]
