# Generated by Django 4.2.9 on 2024-01-12 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('domicilio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ficha_medica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('saldo', models.IntegerField()),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'), ('Gasto', 'Gasto'), ('Ajuste', 'Ajuste')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('libre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('arancel1', models.PositiveIntegerField(blank=True, null=True)),
                ('arancel2', models.PositiveIntegerField(blank=True, null=True)),
                ('arancel3', models.PositiveIntegerField(blank=True, null=True)),
                ('arancel4', models.PositiveIntegerField(blank=True, null=True)),
                ('arancel5', models.PositiveIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='AppDanzaVida.alumno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='AppDanzaVida.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario',
            field=models.ManyToManyField(blank=True, to='AppDanzaVida.horariodisciplina'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='AppDanzaVida.sucursal'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='AppDanzaVida.tipodisciplina'),
        ),
        migrations.CreateModel(
            name='DetalleCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_caja', to='AppDanzaVida.caja')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_caja', to='AppDanzaVida.categoriacaja')),
            ],
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='AppDanzaVida.sucursal'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='responsable',
            field=models.ManyToManyField(blank=True, to='AppDanzaVida.responsable'),
        ),
    ]
