# Generated by Django 4.2.9 on 2024-03-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuota',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
