# Generated by Django 4.2.9 on 2024-01-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
