# Generated by Django 4.2.9 on 2024-01-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0002_alumno_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariodisciplina',
            options={'ordering': ['dia', 'hora_inicio']},
        ),
        migrations.AddField(
            model_name='horariodisciplina',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='AppDanzaVida.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='responsable1_vinculo',
            field=models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Tio', 'Tio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='responsable2_vinculo',
            field=models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Tio', 'Tio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='responsable3_vinculo',
            field=models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tutor', 'Tutor'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Tio', 'Tio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horariodisciplina',
            name='dia',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=20),
        ),
    ]
