# Generated by Django 4.2.9 on 2024-03-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0002_detallecuota_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecuota',
            name='disciplina',
        ),
    ]
