# Generated by Django 4.2.9 on 2024-01-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0002_alter_disciplina_cantidad_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='cantidad_horas',
            field=models.FloatField(choices=[(0.5, 'Media Hora'), (1, 'Una Hora'), (1.5, 'Una Hora y Media'), (2, 'Dos Horas'), (2.5, 'Dos Horas y Media'), (3, 'Tres Horas')]),
        ),
        migrations.AlterField(
            model_name='horariodisciplina',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=20),
        ),
    ]
