# Generated by Django 4.2.9 on 2024-01-15 22:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0003_alter_horariodisciplina_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='cantidad_horas',
            field=models.DecimalField(choices=[(Decimal('0.5'), 'Media Hora'), (Decimal('1.0'), 'Una Hora'), (Decimal('1.5'), 'Una Hora y Media'), (Decimal('2.0'), 'Dos Horas'), (Decimal('2.5'), 'Dos Horas y Media'), (Decimal('3.0'), 'Tres Horas'), (Decimal('3.5'), 'Tres Horas y Media'), (Decimal('4.0'), 'Cuatro Horas'), (Decimal('4.5'), 'Cuatro Horas y Media'), (Decimal('5.0'), 'Cinco Horas')], decimal_places=1, max_digits=2),
        ),
    ]
