# Generated by Django 4.2.9 on 2024-01-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0003_alter_disciplina_cantidad_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
