# Generated by Django 4.2.9 on 2024-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0003_remove_detallecuota_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecuota',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
