# Generated by Django 4.2.9 on 2024-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0004_alter_disciplina_cantidad_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
