# Generated by Django 4.2.9 on 2024-04-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0005_movimientocaja_remove_caja_saldo_caja_saldo_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuota',
            name='movimiento_caja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_cuota', to='AppDanzaVida.movimientocaja'),
        ),
    ]
