# Generated by Django 4.2.9 on 2024-01-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0005_remove_inscripcion_fecha_fin_inscripcion_fecha_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='cantidad_horas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horas_semanales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='horariodisciplina',
            name='cantidad_horas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
