# Generated by Django 4.2.9 on 2024-10-31 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0007_localidad_alter_alumno_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='periodo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='AppDanzaVida.periodo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='responsable1_vinculo',
            field=models.CharField(blank=True, choices=[('mama', 'Mamá'), ('papa', 'Papá'), ('tutor', 'Tutor'), ('hermano', 'Hermano'), ('abuelo', 'Abuelo'), ('tio', 'Tio'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='responsable2_vinculo',
            field=models.CharField(blank=True, choices=[('mama', 'Mamá'), ('papa', 'Papá'), ('tutor', 'Tutor'), ('hermano', 'Hermano'), ('abuelo', 'Abuelo'), ('tio', 'Tio'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='responsable3_vinculo',
            field=models.CharField(blank=True, choices=[('mama', 'Mamá'), ('papa', 'Papá'), ('tutor', 'Tutor'), ('hermano', 'Hermano'), ('abuelo', 'Abuelo'), ('tio', 'Tio'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
