# Generated by Django 4.2.9 on 2024-01-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0010_alter_periodo_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='anio',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persente', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_asistencia', to='AppDanzaVida.alumno')),
                ('detalle_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_asistencia', to='AppDanzaVida.detalleperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='AppDanzaVida.disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='AppDanzaVida.periodo')),
            ],
        ),
    ]
