# Generated by Django 4.2.9 on 2024-01-19 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0011_alter_periodo_anio_detalleasistencia_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleasistencia',
            name='asistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppDanzaVida.asistencia'),
            preserve_default=False,
        ),
    ]
