# Generated by Django 4.2.9 on 2024-01-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDanzaVida', '0012_detalleasistencia_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleasistencia',
            old_name='persente',
            new_name='presente',
        ),
    ]
